### ISSUE TITLE
Support for M1 macs MPS api

### ISSUE THREAD

**Issue by Langhalsdino** [nateraw/stable-diffusion-videos#38] opened 2022-09-17 20:51 UTC
# Feature request

Add support for the M1 chip, since the current macs do not have a Nvidia CUDA GPU.

# Useful Resource 

Pull request for stable-diffusion M1 support
https://github.com/lstein/stable-diffusion/pull/268/files#diff-fde39b496af1173c473e9bccb3ccf07a148c1b050a15f659d5241252268bbb1d

I will do a pull request to fix it

**Comment by danielraffel** [comment] 2022-10-08 10:20
I was trying to run gradio via jupyter on my Mac M1 but think I'm hitting the same issue.

```
from stable_diffusion_videos import interface

interface.launch()
```
I am getting an AssertionError: Torch not compiled with CUDA enabled. I assume there's currently no fallback option?

```
AssertionError                            Traceback (most recent call last)
Cell In [2], line 1
----> 1 from stable_diffusion_videos import interface
      3 interface.launch()

File <frozen importlib._bootstrap>:1075, in _handle_fromlist(module, fromlist, import_, recursive)

File ~/env/lib/python3.10/site-packages/stable_diffusion_videos/__init__.py:73, in _attach.<locals>.__getattr__(name)
     71 elif name in attr_to_modules:
     72     submod_path = f"{package_name}.{attr_to_modules[name]}"
---> 73     submod = importlib.import_module(submod_path)
     74     attr = getattr(submod, name)
     76     # If the attribute lives in a file (module) with the same
     77     # name as the attribute, ensure that the attribute and *not*
     78     # the module is accessible on the package.

File ~/env/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~/env/lib/python3.10/site-packages/stable_diffusion_videos/app.py:14
      6 from .stable_diffusion_pipeline import StableDiffusionWalkPipeline
      7 from .upsampling import RealESRGANModel
      9 pipeline = StableDiffusionWalkPipeline.from_pretrained(
     10     "CompVis/stable-diffusion-v1-4",
     11     use_auth_token=True,
     12     torch_dtype=torch.float16,
     13     revision="fp16",
---> 14 ).to("cuda")
     17 def fn_images(
     18     prompt,
     19     seed,
   (...)
     22     upsample,
     23 ):
     24     if upsample:

File ~/env/lib/python3.10/site-packages/diffusers/pipeline_utils.py:177, in DiffusionPipeline.to(self, torch_device)
    171         if module.dtype == torch.float16 and str(torch_device) in ["cpu", "mps"]:
    172             raise ValueError(
    173                 "Pipelines loaded with `torch_dtype=torch.float16` cannot be moved to `cpu` or `mps` "
    174                 "due to the lack of support for `float16` operations on those devices in PyTorch. "
    175                 "Please remove the `torch_dtype=torch.float16` argument, or use a `cuda` device."
    176             )
--> 177         module.to(torch_device)
    178 return self

File ~/env/lib/python3.10/site-packages/torch/nn/modules/module.py:987, in Module.to(self, *args, **kwargs)
    983         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
    984                     non_blocking, memory_format=convert_to_format)
    985     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
--> 987 return self._apply(convert)

File ~/env/lib/python3.10/site-packages/torch/nn/modules/module.py:639, in Module._apply(self, fn)
    637 def _apply(self, fn):
    638     for module in self.children():
--> 639         module._apply(fn)
    641     def compute_should_use_set_data(tensor, tensor_applied):
    642         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    643             # If the new tensor has compatible tensor type as the existing tensor,
    644             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    649             # global flag to let the user control whether they want the future
    650             # behavior of overwriting the existing tensor or not.

File ~/env/lib/python3.10/site-packages/torch/nn/modules/module.py:662, in Module._apply(self, fn)
    658 # Tensors stored in modules are graph leaves, and we don't want to
    659 # track autograd history of `param_applied`, so we have to use
    660 # `with torch.no_grad():`
    661 with torch.no_grad():
--> 662     param_applied = fn(param)
    663 should_use_set_data = compute_should_use_set_data(param, param_applied)
    664 if should_use_set_data:

File ~/env/lib/python3.10/site-packages/torch/nn/modules/module.py:985, in Module.to.<locals>.convert(t)
    982 if convert_to_format is not None and t.dim() in (4, 5):
    983     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
    984                 non_blocking, memory_format=convert_to_format)
--> 985 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

File ~/env/lib/python3.10/site-packages/torch/cuda/__init__.py:221, in _lazy_init()
    217     raise RuntimeError(
    218         "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
    219         "multiprocessing, you must use the 'spawn' start method")
    220 if not hasattr(torch._C, '_cuda_getDeviceCount'):
--> 221     raise AssertionError("Torch not compiled with CUDA enabled")
    222 if _cudart is None:
    223     raise AssertionError(
    224         "libcudart functions unavailable. It looks like you have a broken build?")

AssertionError: Torch not compiled with CUDA enabled
```

**Comment by Langhalsdino** [comment] 2022-10-08 10:28
You can checkout this branch of the PR (shame on me / i have not integrated the feedback yet).
https://github.com/nateraw/stable-diffusion-videos/pull/39

 I used the environment defined by [INSTALL_MAC.md](https://github.com/lstein/stable-diffusion/blob/main/docs/installation/INSTALL_MAC.md) and in [environment-mac.yaml](https://github.com/lstein/stable-diffusion/blob/main/environment-mac.yaml).

**Comment by danielraffel** [comment] 2022-10-08 17:35
thanks for sharing that. so, I didn't end up creating a new env because I already have the fallback set in my current one (for another variant of SD) and assume there are a number of dependencies. if I can't figure this out I might just try creating a new env. I just checked out your changes and updated these files with your commits

- stable_diffusion_pipeline.py
- stable_diffusion_walk.py
- app.py
- devices.py

Then I ran this again in jupyter

```
from stable_diffusion_videos import interface

interface.launch()
```

Now, I am getting these errors

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [25], line 1
----> 1 from stable_diffusion_videos import interface
      3 interface.launch()

File ~/env/lib/python3.10/site-packages/stable_diffusion_videos/__init__.py:73, in _attach.<locals>.__getattr__(name)
     71 elif name in attr_to_modules:
     72     submod_path = f"{package_name}.{attr_to_modules[name]}"
---> 73     submod = importlib.import_module(submod_path)
     74     attr = getattr(submod, name)
     76     # If the attribute lives in a file (module) with the same
     77     # name as the attribute, ensure that the attribute and *not*
     78     # the module is accessible on the package.

File ~/env/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~/env/lib/python3.10/site-packages/stable_diffusion_videos/app.py:6
      3 import gradio as gr
      4 import torch
----> 6 from .stable_diffusion_walk import SCHEDULERS, pipeline, walk
      7 from .devices import choose_torch_device
     10 def fn_images(
     11     prompt,
     12     seed,
   (...)
     17     upsample,
     18 ):

File ~/env/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_walk.py:12
      9 from diffusers import ModelMixin
     10 from contextlib import nullcontext
---> 12 from .stable_diffusion_pipeline import StableDiffusionPipeline
     13 from .devices import choose_torch_device
     16 device = choose_torch_device()

ImportError: cannot import name 'StableDiffusionPipeline' from 'stable_diffusion_videos.stable_diffusion_pipeline' (/Users/somehuman/env/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_pipeline.py)
```

**Comment by danielraffel** [comment] 2022-10-08 18:38
Actually, I restarted jupyter and now it's kinda sorta running! But, there's a new error...

```
Traceback (most recent call last):
  File "/Users/somehuman/env/lib/python3.10/site-packages/gradio/routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "/Users/somehuman/env/lib/python3.10/site-packages/gradio/blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/Users/somehuman/env/lib/python3.10/site-packages/gradio/blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/somehuman/env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/somehuman/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/somehuman/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/somehuman/env/lib/python3.10/site-packages/stable_diffusion_videos/app.py", line 35, in fn_images
    img = pipeline(
  File "/Users/somehuman/env/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/somehuman/env/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_pipeline.py", line 201, in __call__
    noise_pred = self.unet(
  File "/Users/somehuman/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/somehuman/env/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 263, in forward
    timesteps = timesteps[None].to(sample.device)
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

**Comment by nateraw** [comment] 2022-10-17 23:09
Hey there, the latest version of the code is using `diffusers==0.5.1` and _might_ support mps, but I have no way of checking. If anybody wants to install this repo from main and give it a try, let me know!

```
pip install git+https://github.com/nateraw/stable-diffusion-videos
```

Can then follow instructions from [here](https://huggingface.co/docs/diffusers/optimization/mps#inference-pipeline) to initialize the pipeline for mps.

**Comment by nateraw** [comment] 2022-10-20 04:54
Hey folks, I think M1 may be supported on latest PyPi version now. Can any of you verify if this works?

```python
from stable_diffusion_videos import StableDiffusionWalkPipeline

pipeline = StableDiffusionWalkPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipeline = pipeline.to('mps')

video_path = pipeline.walk(
    ['a cat', 'a dog'],
    [42, 1337],
    fps=5,                      # use 5 for testing, 25 or 30 for better quality
    num_interpolation_steps=5,  # use 3-5 for testing, 30 or more for better results
    height=512,                 # use multiples of 64 if > 512. Multiples of 8 if < 512.
    width=512,                  # use multiples of 64 if > 512. Multiples of 8 if < 512.
)
```

**Comment by danielraffel** [comment] 2022-10-20 06:34
Running this worked for me
`%pip install --upgrade stable-diffusion-videos`

However, running this did not work for me
```
% pip install --upgrade stable-diffusion-videos[realesrgan]
zsh: no matches found: stable-diffusion-videos[realesrgan]
```
When I ran this…
```
from stable_diffusion_videos import StableDiffusionWalkPipeline

pipeline = StableDiffusionWalkPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipeline = pipeline.to('mps')

video_path = pipeline.walk(
    ['a cat', 'a dog'],
    [42, 1337],
    fps=5,                      # use 5 for testing, 25 or 30 for better quality
    num_interpolation_steps=5,  # use 3-5 for testing, 30 or more for better results
    height=512,                 # use multiples of 64 if > 512. Multiples of 8 if < 512.
    width=512,                  # use multiples of 64 if > 512. Multiples of 8 if < 512.
)
```
I got the following output
```
/Users/somehuman/env/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/somehuman/env/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: (__ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE)
  Referenced from: '/Users/somehuman/env/lib/python3.10/site-packages/torchvision/image.so'
  Expected in: '/Users/somehuman/env/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib'
  warn(f"Failed to load image Python extension: {e}")
Fetching 16 files: 100%
16/16 [00:00<00:00, 656.36it/s]
/Users/somehuman/env/lib/python3.10/site-packages/torch/amp/autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/Users/somehuman/env/lib/python3.10/site-packages/stable_diffusion_videos/stable_diffusion_pipeline.py:513: UserWarning: The operator 'aten::lerp.Scalar_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  embeds = torch.lerp(embeds_a, embeds_b, t)
100%
51/51 [00:52<00:00, 1.07it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
100%
51/51 [00:48<00:00, 1.02it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
100%
51/51 [00:48<00:00, 1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
100%
51/51 [00:48<00:00, 1.07it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
100%
51/51 [00:47<00:00, 1.06it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
```

**Comment by nateraw** [comment] 2022-10-20 17:27
I turned the interface into a wrapper.

```python
from stable_diffusion_videos import Interface

interface = Interface(pipeline)
interface.launch()
```

**Comment by danielraffel** [comment] 2022-10-20 23:38
hmm...I gave this a try
```
from stable_diffusion_videos import Interface

interface = Interface(pipeline)
interface.launch()

```

still getting errors, any ideas?
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [6], line 1
----> 1 from stable_diffusion_videos import Interface
      3 interface = Interface(pipeline)
      4 interface.launch()

ImportError: cannot import name 'Interface' from 'stable_diffusion_videos' (/Users/somehuman/env/lib/python3.10/site-packages/stable_diffusion_videos/__init__.py)
```

**Comment by nateraw** [comment] 2022-10-22 02:32
weird that import should be working just fine...not sure what's going on there. Can't reproduce in Colab

**Comment by nateraw** [comment] 2022-11-09 15:42
Believe this issue is resolved. Closing for now

**Closed by nateraw** 2022-11-09 15:42 UTC
